### ISSUE TITLE
Issues running in a subdirectory

### ISSUE THREAD

**Issue by indigo423** [matcornic/hugo-theme-learn#107]
I would like to publish the generated documentation in a subdirectory, for example, something like https://docs.myproject.org/{tool}/{version}.

Where `{tool}` is a namespace for the software which uses Hugo and the learn theme and `{version}` is the documentation generated for a specific version of the software.

I tried several options in the config.toml like `relativeURLS` and `canonifyurl` without any success. Mainly driven by the discussion here: https://discourse.gohugo.io/t/canonifyurls-relativeurls-interaction/5448

The links to CSS, images and JavaScript where always expected in `/`. I use Hugo in version 0.32.4 and I'm not sure if this is a Hugo or theme related issue. Tips and hints would be appreciated.

Thank you in advance

**Comment by matcornic** [comment]
Could you paste here your `config.toml` configuration file ? You need to set `baseurl`

**Comment by indigo423** [comment]
I got it to work when I use the `hugo serve --baseURL` argument. Thank you for feedback.
