### ISSUE TITLE
Handling more than 2 levels

### ISSUE THREAD

**Issue by matcornic** [matcornic/hugo-theme-learn#11]

**Comment by michaeltlombardi** [comment]
This is the only feature keeping me from jumping ship from MkDocs to Hugo with this theme. :) Glad to see it's already being investigated!

**Comment by davistodt** [comment]
Love the theme, and likely to use it for our team's documentation once the third level of pages has been implemented... How far along is this solution?

**Comment by materkey** [comment]
At what stage is the development of this enhancement?

**Comment by matcornic** [comment]
@materkey not really started. Code base changed a lot with latest commits, so first PR on this subject might not suit with current code base.

Do you want to work on it ?

**Comment by vjeantet** [comment]
Hello @matcornic, on my forked version, i've coded 5 levels of menus.

https://github.com/vjeantet/hugo-theme-docdock

Feel free to cherry pick the code as you want.

* everything happens in menu.html partial
* caveat : menu structure depends on "parent-child" info set on each content page.
