### ISSUE TITLE
Missing --MAIN-HOVER-color

### ISSUE THREAD

**Issue by mdavids** [matcornic/hugo-theme-learn#111]
Theme theme-blue.css, theme-red.css and theme-green.css refer to MAIN-HOVER-color:

background-color: var(--MAIN-HOVER-color);

however, they don't define it. 

As a result of this the animation of the line beneath links (when hovered over), does not work.

An easy fix is to add MAIN-HOVER-color.

In theme-blue.css this would be something like:

--MAIN-HOVER-color:#167ad0; /* Color of hovered links animation ul */

This is the color used in --MAIN-LINK-HOVER-color
(the other themes can be fixed likewise).

Another, probably more appropriate solution would be to change:

background-color: var(--MAIN-HOVER-color);
into
background-color: var(--MAIN-LINK-HOVER-color);

**Comment by matcornic** [comment]
Well spotted. Would you want to make a PR ?

**Comment by mdavids** [comment]
Sorry for adding the PR's as separate issues, could probably have been done more efficient ;-)

**Comment by matcornic** [comment]
@mdavids thanks !
