### ISSUE TITLE
Searching in all the site

### ISSUE THREAD

**Issue by matcornic** [matcornic/hugo-theme-learn#12]

**Comment by MarcAudefroy** [comment]
Peut-être via lunr.js?

**Comment by matcornic** [comment]
@gwleclerc avait justement commencé avec Lunr. Mais il avait pas terminé. On espérait que Hugo fournisse un truc automatisé d'ici là ^^.
Mais c'est pas encore le cas.

**Comment by gwleclerc** [comment]
Normalement tout est fonctionnel sur la branche search pour prendre un index lunr.js.
Le problème c'est que la génération de l'index ne peut pas se faire dans le thème. On peut juste s'attendre à ce qu'un fichier JSON soit disponible à un endroit et le prendre comme l'index.

**Comment by yesnault** [comment]
c'est pas dérangeant que lancer un truc au moment de la génération si besoin.

**Comment by matcornic** [comment]
Oui, ce n'est pas dérangeant, mais ce serait pas mal qu'Hugo le fasse tout seul, au moment du `hugo serve`

Parce que dans ce contexte, quand tu es en mode `watch` (Hugo reprend en compte les modifications), la génération de l'index Lunr ne se fera pas en automatique. Tu es obligé de relancer la génération à la main.

Donc tu perds la simplicité de lancement d'Hugo. C'est pour ça qu'on n'avait pas intégré Lunr directement, en attendant qu'Hugo fasse quelque chose. C'est en cours, mais la milestone n'est pas définie : https://github.com/spf13/hugo/pull/1853

**Comment by yesnault** [comment]
La milestone n'est pas définie et pas prête de l'être visiblement :) Y-a moyen de merger la branche quitte à l'enlever quand ce sera dispo sur hugo ?

**Comment by gwleclerc** [comment]
Je ferais ça ce soir après le meetup go ;)

**Comment by matcornic** [comment]
Done with Lunr ! https://matcornic.github.io/hugo-learn-doc/basics/installation/#enable-search-functionality

Could be re-opened if Hugo makes search native.
