### ISSUE TITLE
Files in public folder not rendering correctly. But running locally by "hugo serve" is fine.

### ISSUE THREAD

**Issue by sarahvc** [matcornic/hugo-theme-learn#125]
Hi,

I'm using this theme to build an a11y guideline, and I really like this theme. 

Everything is fine when I do "hugo serve" and run the site locally. However, the files in the public folder(generated by command "hugo") is not rendering correctly. All the links in menu are broken and all the css and js are not working. I found that the home page would be rendering correctly if I change the css href in the index.html from `<link href="/css/nucleus.css?1517851801" rel="stylesheet">` into `<link href="css/nucleus.css?1517851801" rel="stylesheet">`. And href in other pages requires different changes to work properly(e.g. change to `<link href="../../css/nucleus.css?1517851801" rel="stylesheet">`). It's obviously not a good idea to do all the changes manually. I'm not experienced with front-end, and I'm puzzled by this. I'd like to ask for some hint or help. Thanks a lot!!!

Best,
Wei

**Comment by ryanjaeb** [comment]
I think this is because of the way Hugo handles URLs with `relURL` .  It looks like the behavior is controller by the config options [relativeURLs](https://gohugo.io/content-management/urls/#relative-urls) and [uglyURLs](https://gohugo.io/content-management/urls/#ugly-urls).

I haven't tested it beyond a cursory change, but, if you want to run the site off a local filesystem, you should be able to set the above two config properties.  Ex: (`config.toml`)

```toml
baseURL = "//example.org"
relativeURLs = true
uglyURLs = true
```

**Comment by epogrebnyak** [comment]
@matalo33 - why is this closed so silently? Wouldn't it be necessary to add @ryanjaeb seuggection to default config toml? Without it the css paths drop and the user is left wth nothong in `publc` or `docs` folder. I have exactly the same behavior as described in this issue.

```
baseURL = "//example.org"
relativeURLs = true
uglyURLs = true
```

Here is a similar call in StackOverflow, even though a different theme probably. https://stackoverflow.com/questions/55230727/hugo-not-rendering-of-index-html-in-public-folder-locally

**Comment by matalo33** [comment]
OP thumbed up a response.
It's a Hugo issue not theme specific.
It was 8 months since the last reply without follow-up.

**Comment by epogrebnyak** [comment]
> OP thumbed up a response.

I did, OP did not.

> It's a Hugo issue not theme specific.

Can an explaination fit into https://learn.netlify.com/en/basics/installation/#build-the-website ?

`hugo` command does not build a web site with proper CSS, unless changes made to configuration.

Do you know a place in Hugo / discource documentation where adressed?

**Comment by Kp-2019** [comment]
thanks

**Comment by Kp-2019** [comment]
same issue, it works, thanks!
