### ISSUE TITLE
Submenu items only visible if parent is active

### ISSUE THREAD

**Issue by matalo33** [matcornic/hugo-theme-learn#126]
I'd like to specify that only Nth level items in my menu are only visible if the parent page is active. This may be better explained with an example:

This is my example menu layout. In this example Chapter One (bold) is selected. There are only 2 levels of submenu displayed 

- **Chapter One**
- Chapter Two
  - Submenu 1
    - Submenu 2
- Chapter Three

Once my user navigates to Submenu 2 I would like the additional Submenu 3 items to be visible in the menu

- Chapter One
- Chapter Two
  - Submenu 1
    - **Submenu 2**
      - Submenu 3
      - Submenu 3
      - Submenu 3
- Chapter Three

I can't see any feature in the documentation or in the source code (layouts/partials/menu.html) that might allow for this.

Did I miss something and is this possible already? Or is this a feature that has been requested in the past and is being considered?

Thanks

**Comment by matcornic** [comment]
Hello @matalo33 ! Actually it's not implemented, but requested in the issue #88. I'm closing this issue in favour of the other one.

We have to find a nice way to: tell the user that a page has children (typically an arrow) *and* keep the arrow for visited pages.
