### ISSUE TITLE
How to add KaTeX javascript to the theme

### ISSUE THREAD

**Issue by walkccc** [matcornic/hugo-theme-learn#127]
The document doesn't specify where to add the javascript.

I want to display my math equation using KaTeX by adding the following codes:

```js
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-beta1/katex.min.css" integrity="sha384-VEnyslhHLHiYPca9KFkBB3CMeslnM9CzwjxsEbZTeA21JBm7tdLwKoZmCt3cZTYD" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-beta1/katex.min.js" integrity="sha384-O4hpKqcplNCe+jLuBVEXC10Rn1QEqAmX98lKAIFBEDxZI0a+6Z2w2n8AEtQbR4CD" crossorigin="anonymous"></script>
```

Is it possible? Thanks a lot

**Comment by matcornic** [comment]
Simply override `custom-header` (for CSS) and `custom-footer` (for Javascript) partials, as explained [here](https://learn.netlify.com/en/basics/style-customization/)

**Comment by walkccc** [comment]
After adding 

```js
<!-- Partial intended to be overwritten to add custom headers, like CSS or any other info
<style type="text/css">
    /* Custom css */
</style>
-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-beta1/katex.min.css" integrity="sha384-VEnyslhHLHiYPca9KFkBB3CMeslnM9CzwjxsEbZTeA21JBm7tdLwKoZmCt3cZTYD" crossorigin="anonymous">
```

in `custom-header.html`

and

```js
<!-- Partial intended to be overwritten with tags loaded at the end of the page loading (usually for Javascript) 
<script>
    console.log("running some javascript");
</script>
-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-beta1/katex.min.js" integrity="sha384-O4hpKqcplNCe+jLuBVEXC10Rn1QEqAmX98lKAIFBEDxZI0a+6Z2w2n8AEtQbR4CD" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-beta1/contrib/auto-render.min.js" integrity="sha384-IiI65aU9ZYub2MY9zhtKd1H2ps7xxf+eb2YFG9lX6uRqpXCvBTOidPRCXCrQ++Uc" crossorigin="anonymous"></script>
<script>renderMathInElement(document.body);</script>
```

in `custom-footer.html`

It still not work. 
Is there any approach to render the math equation by KaTeX?

**Comment by matcornic** [comment]
Did you create your own `custom-header.html` ? Or update the theme one ?

**Comment by walkccc** [comment]
Thanks, this seems to work, but there is still some situations not working.

For example: `\begin{equation}`, `\begin{array}`, `$$`.

Should I put the `markup: mmark` in the article first?

Even I put it in the article first, there is still some error, and `markup: mmark` will disable the TOC(table of contents) functions.

Thanks a lot again!

**Comment by ColtonProvias** [comment]
You should be able to do it with the default engine.

```
This equation $ c\_0 = a\_0 + b\_0 $ appears inline.

This equation appears as a centered block:

$$ c\_0 = a\_0 + b\_0 $$
```

The only gotcha I really notice is that as markdown uses underscores for italics, you have to escape them as I did for them to work.

**Comment by walkccc** [comment]
I know the escape character you mentioned. I'm currently using `MathJax` + `markup: pandoc` because it is compatible to many math equations, and I can write my MarkDown in a neat way. But the downside is that it is really slow. Is it possible to use `KaTeX` and also write in a neat way?

**Comment by ColtonProvias** [comment]
You may want to refer to https://khan.github.io/KaTeX/function-support.html for an idea of what you can and can't do with KaTeX. The only character needing escaping in blackfriday I know of is the underscore. I haven't tried with other rendering engines.
