### ISSUE TITLE
Favicon doesn't show up in the Github Pages

### ISSUE THREAD

**Issue by walkccc** [matcornic/hugo-theme-learn#130]
The favicon shows up in the localhost:1313, but doesn't show up in my Github Pages.
 
I don't know what causes this and I'm sure I've put the favicon.png in the correct path both in `/static/images/favicon.png` and `/themes/hugo-theme-learn/static/images/favicon.png`. 

How can I fix this? Thanks a lot!

**Comment by matcornic** [comment]
It's a bug : favicon does not support on websites with custom path.

https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/partials/favicon.html

**Comment by walkccc** [comment]
Thanks, it's now correctly working
