### ISSUE TITLE
Is it possible to record search terms?

### ISSUE THREAD

**Issue by pgorod** [matcornic/hugo-theme-learn#134]
Hi! I am wondering if there is any way to change this theme so that it is possible to record the terms that users search for?

We have a documentation site and it would be nice to have a list of what people are searching for, since that will have many clues about which documentation material needs to be written next.

Is it possible with the current search architecture? How?

EDIT: One way to do this would be to have some javascript call out an HTTP request that could be pointed at the statistics engine (like Piwik or Google Analytics).

Thanks!

**Comment by matcornic** [comment]
You could add some Javascript for sending the searched data to another server like Google Analytics does for visited pages. Nothing is impossible but you will have to implement it yourself.
Did you try https://matomo.org/ (ex Piwik), it may help you !

**Comment by pgorod** [comment]
Hi, thanks for your fast reply. We already run Piwik, my question is just how to connect it with the current search architecture. 

I confess I don't know the Search currently works in Learn Theme. If you can just point me to the place in the code where you think the call should be added, I'll try and take it from there.

I have an intuition that one thing will be difficult: since search is find-as-you-type, when people search for `Cats`, you would get a query for `C`, another for `Ca`, another for `Cat` and finally one for `Cats`. And avoiding this might not be simple... you never know when the person is still going to type more characters.

**Comment by matcornic** [comment]
Search is based on searching in a json file containing page content (with Lunr). This file is exposed by Hugo thanks to the file [index.json](https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/index.json). Then search is done by https://github.com/matcornic/hugo-theme-learn/blob/master/static/js/search.js

You can see a rendered example file at https://learn.netlify.com/en/index.json

To avoid the problem of searching for each letter, the usual solution is throttle/debounce function (ex: http://benalman.com/projects/jquery-throttle-debounce-plugin/). Then add needed Javascript in your custom [custom-footer](https://learn.netlify.com/en/basics/style-customization/)

I don't know much about Piwik and whether you can send this kind of data though.

**Comment by pgorod** [comment]
Thanks a lot for the detailed information. I won't be able to work on this right away but I will definitely save this precious guidance for when get a chance.

BTW; you might like to see the site that went live on Thursday, it's for a quite big open-source project: docs.suitecrm.com
