### ISSUE TITLE
 Json files from Github API not retrieved by netlify while building the site

### ISSUE THREAD

**Issue by andrese52** [matcornic/hugo-theme-learn#135]
I'm not sure if this is an issue of this theme specifically but here I go. 

I've been trying to add a credits section like the one you show [here](https://learn.netlify.com/en/credits/). While building the site with `hugo` in my linux PC it works perfectly and I get the Github API data. However, whenever I commit the changes and netlify deploys the site, the section (where the github metrics are shown) disappears completely.

 Is this an issue with netlify or this theme?  or can we include our Github API token in a specific place of netlify to authorize the JSON API download?

I can also upload the rendered site, but it would be good that the metrics update automatically.

**Comment by matcornic** [comment]
I already faced this kind of issue, but it was not automatic. Maybe Github blocks some IPs of Netlify.

Is it automatic on your side ? You have the problem for each build ?
Did you get errors in the browser console ? or in the logs of the build ?
