### ISSUE TITLE
next/previous page indicators bool?

### ISSUE THREAD

**Issue by willwade** [matcornic/hugo-theme-learn#136]
I like them but.. is there any way to turn off the next/previous page indicators? (e.g. in frontmatter for a section?)

**Comment by matcornic** [comment]
Nope, but feel free to contribute :)

**Comment by willwade** [comment]
Fair comment ;)

I've quickly hacked this. I'm pretty sure it works as expected. I would have preferred to deal with it per section or all site params..

**Comment by matalo33** [comment]
Fixed in #184
