### ISSUE TITLE
Translated page gets extra "chapter" div

### ISSUE THREAD

**Issue by pgorod** [matcornic/hugo-theme-learn#140]
Hi. I am facing a problem with this Theme which is making it very hard to get my CSS right :-)

You can see it live here: 
https://docs.suitecrm.com/
https://docs.suitecrm.com/es/

These two pages have an HTML difference: the translated one has `<div id="chapter">` while the English one doesn't. I don't suppose this should be happening...

Source is here: https://github.com/salesagility/SuiteDocs

**Comment by DirtyF** [comment]
Not a bug in the theme, you have to remove `chapter:true` from the ES homepage.

**Comment by pgorod** [comment]
Ahh silly me, I didn't realize that file was involved, I thought everything was coming from `layouts/index.html`

Thanks Frank! And sorry for the noise, Mathieu!
