### ISSUE TITLE
Table of Content does not work with Asciidoctor

### ISSUE THREAD

**Issue by indigo423** [matcornic/hugo-theme-learn#141]
We use Asciidoctor for our documentation and noticed the table of content in the navbar does not work. When I use Markdown the Table of Content is shown correctly.

**Comment by matcornic** [comment]
Wont fix, this is Hugo related. See https://github.com/gohugoio/hugo/issues/1687

**Comment by theletterf** [comment]
@indigo423 Posted a workaround here: https://discourse.gohugo.io/t/table-of-contents-not-generated-with-asciidoctor-documents-as-source/15870
