### ISSUE TITLE
Nested Folders with just title and no content not supported!

### ISSUE THREAD

**Issue by kbhutiya** [matcornic/hugo-theme-learn#142]
When a parent folder just needs to have a Title in index.md(don’t even want index.md,just a title ) but don’t want to show content!It mean index.md shouldn’t be mandatory for each folder Is there any workaround for this?

**Comment by matalo33** [comment]
Are you still tracking this ticket? Please could you explain the issue in more detail? I don't quite understand the issue you're facing.

**Comment by kbhutiya** [comment]
Yes,so i have a project with a lot of folders where basically some of the folders are empty but i want to show  that folder in my website! For that i would have to create an index.md file  for each folder which have title as front matter in order to show it in website! Now  my question is  there any way,i don’t have to create an index.md file for each folder but still can show that folder in my website ! I

**Comment by matalo33** [comment]
Ok I understand now. I don't believe what you describe is possible, without the index file (or even any file) there is no markdown content for hugo to render. It would require modification of hugo to "guess" what to render if no files were present in a folder.

**Comment by kbhutiya** [comment]
Okay !Thank you!
