### ISSUE TITLE
Actively maintained?

### ISSUE THREAD

**Issue by matalo33** [matcornic/hugo-theme-learn#143]
Hiya @matcornic,

Is this project being actively maintained? There are a number of pull requests which have been awaiting feedback or awaiting merge since the start of the year.

I'm actively using this theme at work. I can offer some of my time it would be helpful.

Could you share your thoughts on maintaining this project in the future?

Thanks,
Matt

**Comment by mfaure** [comment]
According to his twitter account, @matcornic has just got a new (exciting) job. Perhaps you may contact him at https://twitter.com/matcornic

**Comment by mfaure** [comment]
Well, I twitted to @matcornic https://twitter.com/mfaure/status/1015166899402010625 Let see :)

**Comment by matcornic** [comment]
Sent an invite to @matalo33 🎉

**Comment by matcornic** [comment]
@matalo33 I created a draft wiki page for dev guidelines : https://github.com/matcornic/hugo-theme-learn/wiki/Guidelines 

Feel free to share your thoughts.

**Comment by matalo33** [comment]
Thanks @matcornic, Dev Guidelines look good, and I'll help out wherever I can

**Comment by matalo33** [comment]
@matcornic you might have noticed I found some time to respond to tickets & review PRs :) I am planning to merge back some changes from a fork over the next couple of weeks.

Are you happy for me to merge PRs which are *not* my own? For my own PRs I will tag you and request review, and not merge my own

**Comment by matcornic** [comment]
@matalo33 yes thanks a lot 🙏

**Comment by matcornic** [comment]
@matalo33 Merge your own PRs when you want, once I approved it. It will be more convenient for you :)
