### ISSUE TITLE
Q. about TableOfContents

### ISSUE THREAD

**Issue by yesnault** [matcornic/hugo-theme-learn#15]
Hi,

You define TableOfContents in hugo-theme.css without using it (it's display:none). Do you plan to use it by configuration ?

Thks a lot

**Comment by matcornic** [comment]
If you want to use the table of contents, just set `toc=true` in the header of your page.

**Comment by yesnault** [comment]
Seems not working, with https://github.com/matcornic/hugo-theme-learn/blob/master/static/css/hugo-theme.css#L69
That said, I have a big toc, with long titles. I need to put toc below title, and a button to toggle toc if we scroll down. I'll try to do something, you will have a PR (perhaps ;) ) after.
