### ISSUE TITLE
Modify text size and alignment

### ISSUE THREAD

**Issue by darrenchan** [matcornic/hugo-theme-learn#160]
Just wondering where do I modify text size and alignment for _index.md and md files generated in html?
Thanks!

**Comment by dmiracle** [comment]
You can add your own css to the site/static/css directory if you want. Check out the section in the docs about [style customization](https://themes.gohugo.io//theme/hugo-theme-learn/en/basics/style-customization/).

**Comment by leonstafford** [comment]
Looking at that documentation with fresh eyes, I'm really unsure of this, too.

What does the following mean?

> Don't forget to include `style` HTML tag directive in your file

**Context**

> custom-header: custom headers in page. Meant to be overwritten when adding CSS imports. Don’t forget to include style HTML tag directive in your file

**From**

[https://themes.gohugo.io//theme/hugo-theme-learn/en/basics/style-customization/](https://themes.gohugo.io//theme/hugo-theme-learn/en/basics/style-customization/)

[https://github.com/matcornic/hugo-theme-learn/blob/master/exampleSite/content/basics/style-customization/_index.en.md](https://github.com/matcornic/hugo-theme-learn/blob/master/exampleSite/content/basics/style-customization/_index.en.md)

Based on the example site, which has a `layouts/partials/custom-footer.html`

And the instruction above to put css into `static/css`, I was hoping to create a `static/css/something.css` and link to it from a `<link>` tag within `layouts/partials/custom-header.html`.

Happy to create a PR to make that page clearer, but I first need to understand it myself :stuck_out_tongue:
