### ISSUE TITLE
Mermaid node with links not clickable

### ISSUE THREAD

**Issue by leonstafford** [matcornic/hugo-theme-learn#168]
As per the Interaction section in the [Mermaid docs](https://mermaidjs.github.io/flowchart.html)

The following markup will create linkable nodes:

`click downloading "/en/troubleshooting/downloading/"`

This does indeed create clickable nodes within the Learn theme, but without showing a `cursor: pointer` style.

I have confirmed that by:

 - adding `.node.clickable { cursor: pointer; }` to custom CSS and adding the `clickable` class via FireFox's inspector, the node's will show the expected pointer cursor on hover.

Not sure if this is simply a library update or what is required, but will start taking a look, as I'm loving these Mermaid charts!

**Comment by matalo33** [comment]
Fixed in #169
