### ISSUE TITLE
Cross Site Scripting vulnerability

### ISSUE THREAD

**Issue by jmaxallen** [matcornic/hugo-theme-learn#181]
I really like your theme. But our static code analysis found a security issue that would prevent us from using it! I'm sorry that I don't know JavaScript well enough to offer a quick PR.
```
Type             Severity   Line#   File
============================================================================================
Client_DOM_XSS   High       71      /website/themes/hugo-theme-learn/static/js/hugo-learn.js
```

**Comment by jmaxallen** [comment]
I tried putting it in a simple `encodeURI()`, and it cleared it up! I'll create a pull request.
https://github.com/matcornic/hugo-theme-learn/pull/182

**Comment by matalo33** [comment]
Thank you!
