### ISSUE TITLE
Icons not working properly

### ISSUE THREAD

**Issue by ebrondol** [matcornic/hugo-theme-learn#183]
Hi, I have recently update the website with the fix of the search function (PR #177) and now it works! Thanks! But another issue come up: the icons are either not visible anymore or replaced by squares.
Is someone else experiencing the same issue? Is maybe already a work going on to fix it?

**Comment by ebrondol** [comment]
Sure, this is the screenshot of my website after I update the theme:
![screenshot from 2018-10-20 13-01-57](https://user-images.githubusercontent.com/5331004/47254909-7afeb400-d468-11e8-8d42-a525ca92fbec.png)
As you can see some icons on the left are visible (like GitHub, camera, books, etc), while the arrow and the search icons are replaced by a square. I am using Google Chrome Version 69.0.3497.81 (Official Build) (64-bit), but I have a very similar effect with Firefox.

**Comment by matalo33** [comment]
Sorry I can't reproduce this. Is your repository public?

**Comment by ebrondol** [comment]
Hi, yes, the repository is public, you can find it here:
https://gitlab.cern.ch/CLICdp/HGCAL/HGCAL_sensor_web/
Thank you very much!

**Comment by tanzaho** [comment]
Hi @ebrondol ,
They've updated font-awesome library link in the header.html file.

In your code, you have a custom one, change this line : https://gitlab.cern.ch/CLICdp/HGCAL/HGCAL_sensor_web/blob/master/layouts/partials/header.html#L13

for this: `<link href="{{"css/fontawesome-all.min.css" | relURL}}{{ if $assetBusting }}?{{ now.Unix }}{{ end }}" rel="stylesheet">`

**Comment by ebrondol** [comment]
Thank you @tanzaho, the fix is working! I should be more careful with that!
