### ISSUE TITLE
Chromium 55 / 56 - Scroll Broken

### ISSUE THREAD

**Issue by yesnault** [matcornic/hugo-theme-learn#20]
Hi,

Scroll seems really broken with chromium 55 / 56 (ok with 51) --> there's an auto-scrool UP, very strange...

Thks,

**Comment by yesnault** [comment]
fixed with e9ea37f6839f26dd85484b8043c6d80e13bf3058, thanks @gwleclerc  !

**Comment by matcornic** [comment]
It was because of sticky-kit, used for the sticky bar. Thanks to https://github.com/leafo/sticky-kit/issues/180 , it's now fixed.
