### ISSUE TITLE
Add imgbot to auto-optimize images

### ISSUE THREAD

**Issue by coliff** [matcornic/hugo-theme-learn#201]
Your image file sizes would be reduced by **31%** 🎉

## Details

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /static/images/favicon.png | 1.22kb | 0.59kb | 51.48% |
| /exampleSite/content/basics/installation/images/chapter.png | 85.71kb | 46.66kb | 45.56% |
| /exampleSite/content/cont/pages/images/pages-chapter.png | 243.33kb | 152.42kb | 37.36% |
| /exampleSite/content/basics/style-customization/images/red-variant.png | 380.82kb | 239.39kb | 37.14% |
| /exampleSite/content/basics/style-customization/images/blue-variant.png | 380.01kb | 238.93kb | 37.13% |
| /exampleSite/content/basics/style-customization/images/green-variant.png | 381.74kb | 240.20kb | 37.08% |
| /exampleSite/content/cont/pages/images/pages-default.png | 310.79kb | 196.47kb | 36.78% |
| /exampleSite/static/images/showcase/tat.png | 405.21kb | 302.69kb | 25.30% |
| /static/images/gopher-404.jpg | 215.36kb | 201.42kb | 6.47% |
| /images/tn.png | 141.37kb | 139.98kb | 0.99% |
| | | | |
| **Total :** | **2,545.56kb** | **1,758.74kb** | **30.91%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

**Comment by matcornic** [comment]
Thanks for the tip, I added the service. 

I tried to force request the optimisation on Imgbot website, but I did not see any PR for now. 

Let's give the bot some time :)

**Comment by coliff** [comment]
cool - I see imgbot worked his magic in #222. :-)
