### ISSUE TITLE
titleCaseStyle

### ISSUE THREAD

**Issue by 1414C** [matcornic/hugo-theme-learn#203]
I created a new entry in my config.toml file to specify titleCaseStyle = "Chicago" in an effort to prevent the capitalization of every character in the single page titles.  This didn't appear to have any effect.

For example, I have a single page setup as follows:

---
title: "This is a Sample Title"
date: 2018-12-07T16:48:02-07:00
weight: 11
draft: true
---

I added the following to my config.toml file:

titleCaseStyle = "Chicago"

The title renders as: 'THIS IS A SAMPLE TITLE', rather than 'This is a Sample Title'.

My understanding looking at the chapter.md and default.md archetypes is that the Hugo title function is being applied to the .Name provided in my templates?  I don't really know much about this sort of thing however, so my question is:  How can I control the capitalization settings for the single page 'title:' variable?

thanks!

**Comment by matalo33** [comment]
The only reference I can see to `titleCaseStyle` is [this gohugo commit from 2017](https://github.com/gohugoio/hugo/commit/8fb594bfb090c017d4e5cbb2905780221e202c41).

Is it actually a documented feature? Does it work correctly in other themes?

**Comment by 1414C** [comment]
Hi Matt.  You are correct - titleCaseStyle does not appear in the latest revision of the official Hugo docs.  I was looking at [this tutorial](https://www.codestudies.net/hugo/recipes/titlecasestyle-setting/) which must not be current.

so.....  I hate to ask, but is there a way to change the page titles to mixed case?  I am using your template to document an API and it would be very nice if the page titles rendered using the exact case used in the page's title.

i.e. 
title: "PublicDB.DropIndex"

Thanks for looking at this - I understand and appreciate that you are doing this on your own time.

**Comment by matalo33** [comment]
This uppercase transformation is actually performed by [style.css](https://github.com/matcornic/hugo-theme-learn/blob/master/static/css/theme.css#L462)

```h1 {
    text-transform: uppercase;
```

You should override this value on your website to be `none`.

**Comment by FeiChaoyu** [comment]
theme.css

h1 {
    font-family: "", "Helvetica", "Tahoma", "Geneva", "Arial", sans-serif;
    text-align: center;
    text-transform: none;
    color: #222;
    font-weight: 200;
}
like this!
