### ISSUE TITLE
Asciidoc/Asciidoctor support ?

### ISSUE THREAD

**Issue by PierreR** [matcornic/hugo-theme-learn#21]
Does the theme support `asciidoc` well ?

I am searching for a technical documentation site generator that supports that format.

Thanks for your help.

Cheers

**Comment by matcornic** [comment]
@PierreR Never tried it with this theme but Hugo supports Asciidoc : https://gohugo.io/content/supported-formats/

Just have the `asciidoctor` or `asciidoc` installed on your building machine and you will be able to generate a Hugo website with this theme.

**Comment by PierreR** [comment]
I will need to tweak some css but that looks promising enough. Thanks

![capture-hugo](https://cloud.githubusercontent.com/assets/93115/19786114/99f57cdc-9c9c-11e6-8c99-764df9368bf1.PNG)

**Comment by PierreR** [comment]
Do I need to enable something special to get the `toc` into the sidebar ?

**Comment by matcornic** [comment]
Just set `toc=true` in your page header. Hugo should generate the toc automatically. 

But seeing their doc (https://gohugo.io/extras/toc/), I think it's only available with Markdown.
Only solution would be to use jQuery to generate it or make a PR to Hugo directly :/

**Comment by gwleclerc** [comment]
It seems that toc in asciidoc is supported as there is an issue concerning toc with asciidoc in Hugo 1.5 (https://github.com/spf13/hugo/issues/1687)
