### ISSUE TITLE
Update lunr js

### ISSUE THREAD

**Issue by coliff** [matcornic/hugo-theme-learn#214]
The latest version has lots of bug fixes and improvements.

CHANGELOG:
https://github.com/olivernn/lunr.js/blob/master/CHANGELOG.md

Minified version here:
https://cdnjs.com/libraries/lunr.js/

Shall I make PR?

**Comment by coliff** [comment]
Update: I've tested successfully with v1.0.0 from a CDN.
`https://cdnjs.cloudflare.com/ajax/libs/lunr.js/1.0.0/lunr.min.js`
The later versions of Lunr JS appear to break autocomplete suggestions. Will investigate....

**Comment by matalo33** [comment]
Closed by #237
