### ISSUE TITLE
Automatically generate prev/next

### ISSUE THREAD

**Issue by zmb3** [matcornic/hugo-theme-learn#22]
Is it possible to automatically generate the `prev` and `next` paths in the front matter?

I'm working on a site with a lot of content and manually setting these on each page is not feasible.  Is there some way to automatically generate the links (alphabetically ordering them, perhaps)?

**Comment by matcornic** [comment]
Hello @zmb3 , it's not possible at the moment (and the website of Hugo does the same).
It's obviously a good idea but I'm not sure it's feasible with Hugo + Go templates. I'll look into it, unless you want to contribute on that ;)

For example, [Position](https://godoc.org/github.com/spf13/hugo/hugolib#Position) is a start. I don't think it was available when I created this theme.

Anyway, we should not generate it from alphabetical order, but from :

1. the weights of the pages in section > then by alphabetical order
2. menu order for chapter sections.

It's not so easy but if we can generate arrows at least for pages in the same section, it could be great !

Note : `prev` and `next` are optional and the theme is working well without them (but you loose the arrows).

**Comment by zmb3** [comment]
Thanks for the response. I agree that even 1) would be a huge win.

I'm definitely willing to help out, but I'm not super familiar with hugo and themes so I'll need some guidance.

**Comment by matcornic** [comment]
@zmb3 Done by @lierdakil !
