### ISSUE TITLE
Convert ```mermaid snippet into the actual graph

### ISSUE THREAD

**Issue by massimeddu** [matcornic/hugo-theme-learn#225]
Currently many tools expect to see mermaid graphs into a code block like:

<pre>
```meirmad
  CODE HERE
```
</pre>

but the theme support only the shortcode syntax: {{<mermaid>}}

Please, add the ability to render correctly also the code blocks.

**Comment by matalo33** [comment]
I believe this can only be implemented by upstream hugo rather than the theme.

**Comment by massimeddu** [comment]
Hello @matalo33 

well, I've written a patch that actually implement it: https://github.com/matcornic/hugo-theme-learn/pull/226

It could be seen as a workaround, but it works. For sure the implementation in upstream hugo should be more elegant.

Thanks,

**Comment by pocc** [comment]
Close this issue because #226 has been merged?
