### ISSUE TITLE
[Question][Newbie] it's possible integrate this theme as a blog? 

### ISSUE THREAD

**Issue by jonnyforestGIS** [matcornic/hugo-theme-learn#231]
Hi,
I want to do multilingual blog to share tutorials and documentation of open source software. This theme have nice features and i want to use as blog and share documentation. 

What are the steps needed? I'm newbie in Hugo template construction.

Cheers,
João

**Comment by epogrebnyak** [comment]
Same question. Learn shines as dcoumentation theme, but what about a blog? `hugo new -k ... blog/2020-02-09-is-this-possible`?
