### ISSUE TITLE
Update to lunrJS 2.3.5

### ISSUE THREAD

**Issue by ozobi** [matcornic/hugo-theme-learn#232]
I have it working with the latest lunrJS if you are interested.

Suggestion for typeahead: https://github.com/olivernn/lunr.js/issues/256

https://cdnjs.cloudflare.com/ajax/libs/lunr.js/2.3.5/lunr.min.js

**Comment by coliff** [comment]
Would be great to see LunrJS updated for this theme. Could you open a PR? Or at least maybe post details on how you got it working?

**Comment by matalo33** [comment]
Please feel free to submit a pull request to update this file.

You should include information regarding how you obtained the file submitted in the MR so the reviewer can confirm its authenticity.

**Comment by matalo33** [comment]
Closed by #237
