### ISSUE TITLE
Update to Featherlight 1.7.13

### ISSUE THREAD

**Issue by ozobi** [matcornic/hugo-theme-learn#233]
Works well with a tiny fix: https://github.com/noelboss/featherlight/issues/317

I have a fixed version, this is the original
cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.css

**Comment by matalo33** [comment]
Please feel free to submit a pull request to update this file.

You should include information regarding how you obtained the file submitted in the MR so the reviewer can confirm its authenticity.

**Comment by matalo33** [comment]
Closed by #237
