### ISSUE TITLE
How to add icons to the menu-footer?

### ISSUE THREAD

**Issue by zxdawn** [matcornic/hugo-theme-learn#236]
How to enable icons (Download, Star and Fork) at the menu-footer like the document?

![image](https://user-images.githubusercontent.com/30388627/52409583-d97f9900-2b10-11e9-9711-dfc43f32143b.png)

I checked `menu-footer.html` as mentioned in #95:

```
<p>Built with <a href="https://github.com/matcornic/hugo-theme-learn"><i class="fas fa-heart"></i></a> from <a href="http://getgrav.org">Grav</a> and <a href="http://gohugo.io/">Hugo</a></p>
```

It doesn't include these icons.

**Comment by matalo33** [comment]
`<i class="fas fa-heart"></i>` is a block of code using Font Awesome to draw the heart you see in the footer.

Check the docs here: https://learn.netlify.com/en/cont/icons/

**Comment by zxdawn** [comment]
@matalo33 How about icons (Download, star and fork) above that sentence?

**Comment by matalo33** [comment]
Please read the documentation I linked, it is all explained inside
