### ISSUE TITLE
Failed to get JSON resource by Travis CI

### ISSUE THREAD

**Issue by zxdawn** [matcornic/hugo-theme-learn#238]
I want to add `Credits`. Then, I created https://github.com/matcornic/hugo-theme-learn/blob/master/exampleSite/layouts/shortcodes/ghcontributors.html under `layouts/shortcodes/` directory and `Credits.md` under `content` directory:

```
---
title: Credits
disableToc: true
---

## Contributors

Thanks to them <i class="fas fa-heart"></i> for making hpc-nuist-ap better!

{{% ghcontributors "https://api.github.com/repos/hpc-nuist-ap/hpc-nuist-ap.github.io/contributors?per_page=100" %}}
```

It's fine to generate contents by `hugo` locally.
But, it doesn't work by Travis CI, even though github information are added:

```
$ hugo
Building sites … ERROR 2019/02/07 14:43:04 Failed to get JSON resource "https://api.github.com/repos/hpc-nuist-ap/hpc-nuist-ap.github.io/contributors?per_page=100": Failed to retrieve remote file: Forbidden
Total in 408 ms
Error: Error building site: logged 1 error(s)
The command "hugo" exited with 255.
```

Part of `.travis.yml`:
```
---
install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

before_script:
  - git config --global user.name "hpc-nuist-ap"
  - git config --global user.email "hpc-nuist-ap@users.noreply.github.com"

script:
  - hugo
```

**Comment by matalo33** [comment]
Github is replying with `Forbidden` so your travis job isn't authenticating properly. You need to provide credentials somewhere to allow travis to identify with github via the https api.

Also noticed this shortcode isn't documented, so I opened up #242

**Comment by zxdawn** [comment]
@matalo33 However, it works now. Maybe, keeping `hugo server` working all the time results in too many requests ...
