### ISSUE TITLE
Chapter not appearing as "read" with checkbox, even after all child pages are read.

### ISSUE THREAD

**Issue by nnja** [matcornic/hugo-theme-learn#243]
I'm not sure if this is a feature, a bug or something misconfigured in my setup. 

When all the child pages of a chapter are read and marked with a blue checkbox, the chapter does not show a blue checkbox, even after directly clicking on the page, and navigating to another page.

Any thoughts on how I might troubleshoot this, or is it part of the theme?

Thanks!

![screen shot 2019-02-17 at 9 35 25 pm](https://user-images.githubusercontent.com/2030983/52930178-4e668600-32fc-11e9-8812-ccffff5249ce.png)

**Comment by matalo33** [comment]
Yep, the chapter should display a checkbox once visited. The docs site is correctly providing this. E.g. https://learn.netlify.com/en/cont/

Start by clearing your cache, cookies, session and see if the issue persists. The tick appears by way of a css style applied by javascript which iterates through the menu links and checks if the page appears in session history
https://github.com/matcornic/hugo-theme-learn/blob/master/static/js/learn.js#L372. If the page is found the css style is applied.

**Comment by nnja** [comment]
@matalo33 I cleared out my `public` folder and visited the site in incognito mode, and the issue still persists across all chapters, even when all the child pages are read. I'll investigate further and see if I can come up with a barebones example to demonstrate.

**Comment by matalo33** [comment]
Do you have draft / unpublished pages within the chapter?
