### ISSUE TITLE
Improving accessibility of table of contents

### ISSUE THREAD

**Issue by mavam** [matcornic/hugo-theme-learn#245]
Hi, we're using this theme for our technical documentation. It's works great so far. We have just one issue: the table of contents is rather difficult to spot. You have to hover over the icon in the top to see. Especially for larger documents, we want the ToC to be visible more prominently, ideally on one side or as part of the side menu.

It looks like #101 goes into this direction, but the PR looks a bit abandoned. Any advice on how to improve navigation *within* a page would be much appreciated.

**Comment by matalo33** [comment]
I've been neglecting that PR. I will try get to it this week. In the meantime I'll close this issue as duplicate as it sounds like #101 will solve your needs. Thanks.
