### ISSUE TITLE
where I will get less or scss file

### ISSUE THREAD

**Issue by polodev** [matcornic/hugo-theme-learn#248]
do you have scss or less file for that theme for customization theme a little

**Comment by coliff** [comment]
The SCSS for this theme isn't currently available... but I think it could potentially be a good idea to include SCSS and use Hugo Extended ([Pipes](https://gohugo.io/hugo-pipes/)) to concatenate and minify the SCSS at build time. It could combine auto-complete.css, featherlight.min.css, hugo-theme.css, perfect-scrollbar.min.css etc.
