### ISSUE TITLE
shortcode children - parameter depth does not work

### ISSUE THREAD

**Issue by worthlutz** [matcornic/hugo-theme-learn#251]
It appears the the depth parameter of the children shortcode is not working.
It does not work in my testing and it does not appear to be working in the theme documentation. See this [doc page](https://learn.netlify.com/en/shortcodes/children/).

**Comment by Chris-Greaves** [comment]
I have created a pull request for fixing this [PR 252](https://github.com/matcornic/hugo-theme-learn/pull/252) 

Feel free to try it out!

**Comment by benhbell** [comment]
This seemed to work for me - but depth property on index page does not work in conjuction

**Comment by worthlutz** [comment]
After merging the pull request #252, it works for me. It does not work with out the merge.

**Comment by matalo33** [comment]
Thanks, closing and will track on #252
