### ISSUE TITLE
children shortcode display as a list on the index page

### ISSUE THREAD

**Issue by countstarlight** [matcornic/hugo-theme-learn#254]
Hello, thank you for your awesome work!

The children shortcode very useful, it is possible use it display all pages on index page as a list? like:

* 1.first chapter page(weight=1)
  * 1.1 first content page(weight=1)
* 2.second chapter page(weight=2)
  * 2.1 second content page(weight=1)

I try to use
```
{{% children sort="weight" %}}
```
or
```
{{% children sort="name" %}}
```

It will display:

* 1.first chapter chapter(weight=1)
* 2.second chapter chapter(weight=2)
* 1.1 first content page(weight=1)
* 2.1 second content page(weight=1)

**Comment by worthlutz** [comment]
@countstarlight  

See PR #252.  It  works with this change.

**Comment by countstarlight** [comment]
@worthlutz 😃Thank you, I will check it.

**Comment by countstarlight** [comment]
@worthlutz Thanks, the lates PR works!
