### ISSUE TITLE
Theme variant does not work consistently for all the menu items

### ISSUE THREAD

**Issue by kshitijkorde** [matcornic/hugo-theme-learn#256]
If I choose a particular theme variant (ex: red), it only works for the first few menu items. It switches to a default "purple" for the remaining items mostly randomly.

**Comment by matalo33** [comment]
I cannot reproduce this issue. When you change the theme variant make sure you restart the hugo server (if running local server) and clear browser cache.

If the issue persists share your repository so that someone can reproduce and investigate.

**Comment by kshitijkorde** [comment]
Hi Matthew,
You are correct. It was because of the browser cache. I will close the issue.
Thanks for your time and prompt feedback. I am closing this issue.
Regards,
Ksh

**Comment by kshitijkorde** [comment]
Closing this issue.
