### ISSUE TITLE
Hugo 0.55 breaks notices

### ISSUE THREAD

**Issue by MarcBruins** [matcornic/hugo-theme-learn#272]
I'm not sure if this a hugo issue or a theming issue. What happens if you use the latest hugo version `0.55` and generate your site a notice looks like this: 

```
<div class="notices info">
This command is only available for github
</div>
```

When using version `0.54` the generated html is: 

```
<div class="notices info">
<p>This command is only available for github</p>
</div>
```

For the notice styling the option without the paragraph doesn't work, that will only render text and no notice is shown.

**Comment by harryleesan** [comment]
The new Hugo release revised how shortcodes are implemented. Currently, content in the `notice` block will be rendered as is. A workaround is to add `{{ $_hugo_config := `{ "version": 1 }` }}` to the `hugo-theme-learn/layouts/shortcodes/notice.html` as shown in https://github.com/gohugoio/hugo/releases. 

Example:

```html
{{ $_hugo_config := `{ "version": 1 }` }}<div class="notices {{ .Get 0 }}" {{ if len .Params | eq 2 }} id="{{ .Get 1 }}" {{ end }}>{{ .Inner }}</div>
```

**Comment by matalo33** [comment]
I expect that many theme users have built the assumption of `<div><p>foo</p><div>` into their overrides, css, etc. Perhaps we should override hugo in the core of the theme?

**Comment by fritzmg** [comment]
It's not just that - I am sure many people (well, or at least us) are also using markdown within the shortcodes. But now that does not work anymore unfortunately.

**Comment by fritzmg** [comment]
For notices there might be a simpler solution:
```
{{ .Inner | markdownify }}
```

**Comment by fritzmg** [comment]
Unfortunately, `| markdownify` alone won't help either: https://discourse.gohugo.io/t/misunderstanding-of-shortcode-syntax-in-0-55/18538/25

**Comment by ChauNamKyNguyen** [comment]
Hi fritzmg,

There are two solutions for this issue:

1. You can wrap up your shortcode with <p> tag
{{% notice tip %}}
<p>
An example text
</p>
{{% /notice %}}

Currently, the hugo generates without <p> tag so the display is wrong.

2. You can use the "hugo-notice" theme here:
https://github.com/martignoni/hugo-notice

Then edit your config.toml
themes = ["hugo-notice", "your-theme"]

Please notice that the "hugo-notice" must be the left most position. With this method, you don't need to insert <p> for your each shortcode. 

But I think this issue muse be fixed officially in the next version.

 Hope it help !

**Comment by fritzmg** [comment]
See also https://github.com/gohugoio/hugo/issues/5975
