### ISSUE TITLE
Alternative Search Options

### ISSUE THREAD

**Issue by Midacts** [matcornic/hugo-theme-learn#275]
Is a search option like this available where end users can type in the search word and the results pop up on the main page for them to navigate to?
![image](https://user-images.githubusercontent.com/3960208/56961012-8cfc9600-6b20-11e9-8fa0-006e20da0259.png)

[Hexo's doc theme](https://zalando-incubator.github.io/hexo-theme-doc/) as well as gitbook have this feature.

(I am currently looking for a gitbook replacement for our markdown documentation static site generator).

**Comment by matalo33** [comment]
Nope sorry, the search you see is the only one available in the theme. If you would like to add support for others then pull requests are more than welcome.
