### ISSUE TITLE
Add a header level offset?

### ISSUE THREAD

**Issue by reedlaw** [matcornic/hugo-theme-learn#277]
```
+++
title = "Test"
+++

## First
```
will generate a `h1` tag for "Test" and a `h2` tag for "First" but it is invalid Markdown (`First header should be a top level header [MD002]` from [mdl](https://github.com/markdownlint/markdownlint)).

Would it be feasible to have header level offset configuration that lets you start the `# First` level markdown at header level 2 (i.e. `h2`)?

**Comment by matalo33** [comment]
I don't believe this theme is the only one in hugo that suffers from this issue. To me the simplest solution would be to disable the lint check for your particular project/website as it isn't applicable to the markdown you are writing.
