### ISSUE TITLE
Hugo deprecation warnings

### ISSUE THREAD

**Issue by almereyda** [matcornic/hugo-theme-learn#289]
Hugo warns not to use certain language constructs anymore:

```
WARN 2019/05/30 01:17:21 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2019/05/30 01:17:21 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
WARN 2019/05/30 01:17:21 Page's .UniqueID is deprecated and will be removed in a future release. Use .File.UniqueID.
Total in 13 ms
```

**Comment by almereyda** [comment]
A suitable patch could look similar to

- https://lab.allmende.io/ecobytes/commons/hugo-theme-ecolearn/compare/251f206a7dae4cfdcf21bc246fdc03a97a634544...36d70302e81b17bd17b1bc7ac2285cb6e2464e07

**Comment by almereyda** [comment]
We now get

    WARN 2019/05/30 02:11:39 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}

from the menu.html partial. Unfortunately my go and go templating skills are not enough to construct this into the one-liner where it's needed.

**Comment by DBJDBJ** [comment]
# Me too
