### ISSUE TITLE
Short code button opens in a new tab

### ISSUE THREAD

**Issue by pramodya1994** [matcornic/hugo-theme-learn#305]
When I click on the shortcodes button provided in hugo-learn-theme, a new page opens in a new tab. Is there any way to open this on the same page.

This is the syntax I have used.
```
{{% button href="https://getgrav.org/" %}}Get Grav{{% /button %}}
```

**Comment by matalo33** [comment]
The button shortcode is provided by the content of the file `layouts/shortcodes/button.html`. If you want to change the behaviour of the shortcode your can either:

* (worst) Directly edit the file from the theme, which will potentially cause issues with future theme updates
* (best) Override the shortcode by copying it from the theme into your website e.g.:
    * from: `website/themes/hugo-theme-learn/layouts/shortcodes/button.html`
    * to: `website/layouts/shortcodes/button.html

If you're new to HTML too have a look at https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target
