### ISSUE TITLE
edit link not displayed

### ISSUE THREAD

**Issue by retorquere** [matcornic/hugo-theme-learn#307]
The documentation says "Feel free to update this content, just click the Edit this page link displayed on top right of each page, and pullrequest it", but there's no such link.

**Comment by matalo33** [comment]
<img width="432" alt="Screenshot 2019-07-30 at 21 38 58" src="https://user-images.githubusercontent.com/2432342/62163590-95788e80-b312-11e9-9cc8-c84fb18ca6ef.png">

This relates to the rendered version of the `exampleSite` which is also the documentation.
https://learn.netlify.com/en/
