### ISSUE TITLE
Can I customize the /tags and /tags/term pages?

### ISSUE THREAD

**Issue by retorquere** [matcornic/hugo-theme-learn#308]
I'd like to replace the /tags page with a tag cloud, and the /tags/term to have the section title added to the link (not all my pages have unique titles). How should I go about this? I can't find where /tags and /tags/term get generated.

**Comment by matalo33** [comment]
Yes, you can. This is not something currently offered by the theme so you would have to implement this yourself. I suggest you start by reading https://gohugo.io/templates/.

Any improvements or features you produce are welcome in pull requests.
