### ISSUE TITLE
Is it possible to redirect from one page to another?

### ISSUE THREAD

**Issue by matthewgourd** [matcornic/hugo-theme-learn#31]
Hi there,

I work on the documentation team at Miracl.com. We're thinking of moving our documentation to Hugo but have a requirement for redirects to be set up from chapter pages, so users don't have to read perfunctory intro. text. Is this technically possible? If so, how would I go about doing it? 

To be more specific, if say a visitor clicks on a chapter named "Registering" containing two sub-pages, one with Android instructions and one with iOS instructions, the visitor should be taken directly to the first sub-page, /registering/registering-android rather than its parent, /registering. Hope that makes sense!

Thanks,

Matt

**Comment by matcornic** [comment]
A **quick & dirty** solution is:

1. Overriding `meta.html` partial in your project by creating a `meta.html` in your `layouts/partials` folder
2. Then, add a redirect meta tag `<meta http-equiv="refresh" content="0; url=http://example.com/"/>` only when the current page is a chapter.

In my opinion, creating this partial requires you to have understanding of Hugo, Go templates and this theme. For the first two, go to the official Hugo documentation, and for the third one you could check the  [menu partial](https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/partials/menu.html) to see how the left menu is built.

So, it's technically possible with some tweaking, buts it's not something that will be supported in the future.

Have fun :sweat_smile:

**Comment by joe-kimmel-vmw** [comment]
just leaving for anyone else who finds this in a search:  seems like hugo supports aliases for this use-case: https://gohugo.io/content-management/urls/#aliases
