### ISSUE TITLE
search bar doesn't work

### ISSUE THREAD

**Issue by Liscum** [matcornic/hugo-theme-learn#310]
Hi, I'm sorry to ask that as it is maybe easy to do but I can't make the search work. I have Hugo v0.55.6 with the last version of hugo-theme-learn.
I added the following lines in "config.toml" in my hugo site root folder :
[params]
search = true

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

Then I used "hugo" command to generate static files, it does create the index.json but then after in my browser, the search bar only highlight in yellow. It is not showing propositions like it does on the hugo demo site.
I followed this : https://learn.netlify.com/en/basics/configuration/
and everything I could find on internet related to this, but it's either deprecated or I can't make it work.

Thanks

**Comment by WhizzySimon** [comment]
same
