### ISSUE TITLE
{{ }} don't get expanded

### ISSUE THREAD

**Issue by ypujante** [matcornic/hugo-theme-learn#311]
I apologize if this is a newbie question or if I am missing something but I cannot figure out how to use `{{ }}` syntax in my pages.

I simply created a `content/about/_index.md` page and doing something like:

```
Hello world

{{ partial "logo.html" . }}

<a href="{{ .Sites.First.Home.RelPermalink }}">Home</a>

```

renders the following html:
```
<p> Hello Workd</p>

<p>{{ partial &ldquo;logo.html&rdquo; . }}</p>
  
<p><a href="{{ .Sites.First.Home.RelPermalink }}">Home</a></p>
```

which is obviously not what I was expecting.

**Comment by pgorod** [comment]
Which Hugo version are you using? I am getting something similar with 0.55.6, that used to work well with 0.54.

**Comment by ypujante** [comment]
I am using 0.55.6.

Not being an expert with hugo I cannot figure out whether this is an issue with hugo or this theme. But I have a strong feeling it is hugo itself...

Using {{ }} in html work fine
Using {{ }} in markdown just does not

What does work is using shortcodes like {{% notice info %}}.

It personally baffles me why that would be the case and if you say that used to work it is even more surprising...

**Comment by pgorod** [comment]
For me it's a shortcode that's failing:

```
---
title: "User Guide"
weight: 10
pre: "<b>1. </b>"
---

=== Table of Contents
{{% children depth="3" showhidden="false" %}}
```

**Comment by ypujante** [comment]
That is weird as I do not have this issue with shortcodes. Did you try with one of the shortcodes that comes with the theme?

```
{{% notice info %}}
This is a test
{{% /notice %}}

**Comment by pgorod** [comment]
`children` is a shortcode that comes with the Theme: https://learn.netlify.com/en/shortcodes/children/

I didn't try `notice`. I must say that I am reporting this in second-hand, a colleague of mine got the problems with Hugo 0.55.6, not me (I still have with 0.54). On Monday he can give me more information.

**Comment by pocc** [comment]
This is a hugo question, not a hugo-learn question. Shortcodes can be used in markdown, but `partial` is not a shortcode. You'll want to add your [partial](https://gohugo.io/templates/partials/) to single.html or list.html in layouts/_default, or you a custom file in layouts/partials.

**Comment by pgorod** [comment]
@pocc Yes, I am also convinced it is a Hugo question, because in my case I did not change Learn version, and I did not change page content: I just changed Hugo version. 

But my issue doesn't involve `partial`, only shortcodes. The original issue here _does_ involve `partials`, so according to your comment, these are not the same thing - agreed.

**Comment by pocc** [comment]
@pgorod: Fair point. These are related but not the same, so I think it would be best if you created a separate issue with the data you have collected.

@ypujante: My previous comment is for you. You can't use the `partial` keyword in markdown, you use it in your partials html.

@matcornic: I think this issue is good to close as this is a question of hugo usage.

**Comment by ypujante** [comment]
@pocc I agree with the fact that it is not a problem with the learn theme as I created a brand new test site without the theme and having the exact same problem. 

As a side note, I think it somehow makes no sense for hugo to be based on go templates (`{{ }}` syntax) but somehow you can't use them in content/markdown pages. The only "replacement" that seems to work in content/markdown pages are shortcodes.

So as far as I am concerned it is fine to close this issue if you want to since it is not a problem with this project.
