### ISSUE TITLE
Search locks up browser

### ISSUE THREAD

**Issue by jipperinbham** [matcornic/hugo-theme-learn#314]
hugo version: v0.55.6

When typing into the search bar, the browser locks up and I don't see any errors in the console.

**Comment by matalo33** [comment]
For someone as active as yourself on github I would have expected a somewhat higher quality issue post. There is zero useful information to use here.

Despite the fact this is not a support forum, let's start with the real basic diagnostics:

What site are you loading? Local server or online? Your own site or someone elses?
What browser are you using? Have you tried multiple browsers? Have you tried in private-mode? Have you disabled all extensions?
What does locks-up mean? Use full CPU? If so chrome / etc will kill the tab and give you diagnostic information inside developer tools.

You should also be aware (or could see in the code) that search is provided by a javascript file loaded from the same repository. The very same repository that supports the documentation site at https://learn.netlify.com/en/. And for me running a search in chrome and firefox is working fine.

Please do some basic troubleshooting yourself and provide something useful if you find anything.

**Comment by jipperinbham** [comment]
> For someone as active as yourself on github I would have expected a somewhat higher quality issue post. There is zero useful information to use here.

That's fair. FWIW, I searched all the exiting issues (open and closed) to try and resolve before giving up. I've also found it helpful when repos provide an Issue template so I know the type of info that is valuable when troubleshooting.

> Despite the fact this is not a support forum

Is there somewhere else I should have looked for help? 

> What site are you loading? Local server or online? Your own site or someone elses?

This is an internal docs site we're working to convert to hugo. The issue is reproducible when running `hugo server` and when serving the static assets with nginx. 

> What browser are you using? Have you tried multiple browsers? Have you tried in private-mode? 

The issue seems to happen only with Chrome (including incognito mode) but not with Safari. I do not have Firefox installed but will do so if it would help diagnose further.

> Have you disabled all extensions?

I had not thought to try that but it did not resolve the issue.

> What does locks-up mean? Use full CPU? If so chrome / etc will kill the tab and give you diagnostic information inside developer tools.

After I type at least 3 characters and pause long enough for it to run, the browser stops responding and looking at Activity Monitor shows CPU pegged at 99-100% for the "Google Chrome Helper" process. Chrome never kills the tab (which I found odd) and the developer tools also do not function once it happens so I can't really see what is happening. After several minutes, it finally gives the "Page Unresponsive, would you like to wait or exit page" prompt. 

The only other thing to note that could help is the `index.json` file is ~3MB.

I apologize for not providing more info initially as I was very stumped after trying several things for quite some time today.

**Comment by matalo33** [comment]
It was late in my day too so apologies on my side as well.

I haven't heard of this issue before, especially strange as it only affects a single browser. 3MB for the index.json seems on the large side. Is your site particularly big, and have you had a peek inside the json to check it looks sane (& valid json)?

At a high level, hugo generates the `index.json`, `learn.js` fetches `index.json` into the browser, and `lunr.min.js` is instantiated with the json.

At the time of writing we're only one minor version behind of lunr (https://cdnjs.com/libraries/lunr.js/2.3.5).

If I had to guess I'd say there might be something unexpected in the json file. You could verify by deleting half the content in your site and starting the local server, then doing the same with the other half, just to rule out that it might be an issue with the content.

**Comment by jipperinbham** [comment]
Thanks for the help and suggestions to try and resolve this. We removed a lot of the content and search started working again. As we slowly add more things back maybe something will jump out but hopefully not.
