### ISSUE TITLE
`notices` shortcode not displaying correctly on 0.55.0 and newer

### ISSUE THREAD

**Issue by pjlewisuk** [matcornic/hugo-theme-learn#316]
I have a number of shortcodes that have stopped displaying correctly since Hugo 0.55.0, with no obvious reason why. The shortcodes e.g. (`notice note`, `notice info`, `notice tip`, `notice warning`) are part of the [learn](https://github.com/matcornic/hugo-theme-learn) theme.

When implementing a simple notice like this:
{{% notice info %}}
Some information you want to draw attention to.
{{% /notice %}}

On Hugo 0.54.0 and earlier the notice box displays correctly, but on 0.55.0 and later it does not - there is no coloured border and header on the notice div.

Here's a screenshot of the Firefox Inspector console looking at content generated by Hugo 0.54.0 or earlier:
![Hugo 0.54.0 and earlier](https://pjlewis-aws-static.s3.amazonaws.com/hugo/notices-hugo-0.54.0-and-earlier.png)

And here's the same screenshot for content generated by 0.55.0 and later:
![Hugo 0.55.0 and later](https://pjlewis-aws-static.s3.amazonaws.com/hugo/notices-hugo-0.55.0-and-later.png)

**Comment by coliff** [comment]
I think this is related to this change:
https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown

**Comment by pjlewisuk** [comment]
> I think this is related to this change:
> https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown

Yes indeed, it seems I had an old version of the theme embedded in my Hugo site, so it hadn't taken the necessary updates. All working well now after updating the theme.
