### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by zingyb** [matcornic/hugo-theme-learn#323]
Thanks so much for this great theme!

I've found that shortcodes rather broken with the 2.3.0 release: In particular, the "button" shortcode renders a malformed button into three items and the "notices" shortcode does not render a banner properly.

Both of these are fixed in the latest master. Is it possible to cut a new release or backport the fixes?

**Comment by matalo33** [comment]
Sure, sounds reasonable. I was holding out for some other issues but I will try push 2.4.0 tomorrow.

**Comment by zingyb** [comment]
Sorry to be a pain, but I'd like to issue a friendly reminder. :)

Thanks again!

**Comment by matalo33** [comment]
Done
