### ISSUE TITLE
Parser Error 

### ISSUE THREAD

**Issue by boris779** [matcornic/hugo-theme-learn#337]
I got a parser error, when I remove the line which contains `{{ hugo.Generator }}` everything is fine.

`
boris@xxxx:~/repos/selenium/site/docs_source_files$ hugo server
Error: "xxxxxxx/repos/selenium/site/docs_source_files/themes/hugo-theme-learn/layouts/partials/header.html:6:1": parse failed: template: partials/header.html:6: function "hugo" not defined
`

**Comment by juliancesar** [comment]
I have the same error!

**Hugo Static Site Generator v0.40.1 linux/amd64 BuildDate: 2018-04-25T17:16:11Z**

**Comment by juliancesar** [comment]
@fritzmg, tks! But my linux version is Ubuntu 18.04 and the recommended version is 0.40.1.

https://packages.ubuntu.com/search?keywords=hugo

@ boris779, i used the version 2.3.0 and it worked (`git checkout tags / 2.3.0`)

**Comment by fritzmg** [comment]
> @fritzmg, tks! But my linux version is Ubuntu 18.04 and the recommended version is 0.40.1.

The theme will surely not be able to support such old versions of Hugo.

**Comment by wesruv** [comment]
@juliancesar I ran into the same issue and used the dpkg instructions from: 
https://hostadvice.com/how-to/how-to-install-hugo-on-ubuntu-18-04/

And downloaded the latest Linux 64bit `.deb` file from: https://github.com/gohugoio/hugo/releases

With the latest release the learn theme is working great!
