### ISSUE TITLE
Make Hugo-Theme-Learn Multilingual.

### ISSUE THREAD

**Issue by jodumont** [matcornic/hugo-theme-learn#34]
Hi;

Thanks to port this awesome theme from grav to hugo.

My hope, question is : **How hard would be**; and _If people have interest for it_, to make Hugo-Theme-Learn Multilingual ?

**Comment by matcornic** [comment]
Hello !

Did you try https://gohugo.io/tutorials/create-a-multilingual-site/ ?

Never tested it, but by reading the page, I think it would be possible to create multilingual site without modifying the theme.

**Comment by jodumont** [comment]
@matcornic 
Didnt try with Hugo-Theme-Learn but with an another theme earlier and few times with Jekyll
and you need to edit the theme by changing all string you considere need to being translated
such as: Title, description, tags, categories, dates, ...

**Comment by matcornic** [comment]
Actually, there are only the following static strings used in the theme:
- `Built with love from Grav and Hugo`
- `Edit this page`
- the whole 404 page

All the rest is user content. No dates are displayed by the theme itself.

So, I don't know if it's worth it ^^
