### ISSUE TITLE
Chapters generated even if all child content page(s) have "draft = true"?

### ISSUE THREAD

**Issue by akira-kurogane** [matcornic/hugo-theme-learn#347]
Recently I regenerated my pages and found that the generated output began to include several chapters I had created a long time ago, but which still only have draft pages. To put it another way, it doesn't seem to matter if I run "hugo" or "hugo -D" even though the content pages in half of the chapters are only draft ones.

Does anyone happen to know a 'gotcha' that I might have hit? 

I suspect it is hugo change rather than this theme because it wasn't like this before when I built I using a version of hugo about 3 ~ 6 months older than current. As of today I have hugo v0.57.2/extended from Ubuntu 19.10 repositories.

I had been using hugo-theme-learn as it was from around Apr 2019. I've updated to current and find no difference in regards to generating chapters that only have draft content pages in them.

Just in case: Here is an example of one of the subdirectories of my content that is now being produced in the rendered output: https://github.com/akira-kurogane/mongodb-guide/tree/master/content/perf_guide. There are four content pages in the two levels under there, all of them with "draft= true".

**Comment by matalo33** [comment]
This should be fixed by #354

**Comment by akira-kurogane** [comment]
Thank you for the update! (And apologies I didn't work out the right patch myself.)
