### ISSUE TITLE
Adaptive Scrollbar?

### ISSUE THREAD

**Issue by patriotaki** [matcornic/hugo-theme-learn#368]
is it possible to have the scrollbar be in the same “height” as the current menu i am ?

as you can see in the gif below, when i click a menu it goes back up, i want the scrollbar to stay in that position

https://aws1.discourse-cdn.com/standard10/uploads/gohugo/optimized/2X/f/fc1583f79149611f8c8fa5c597f2e5d77dd6d6d5_2_336x500.gif

thanks

**Comment by Nightshadelink** [comment]
Duplicates: https://github.com/matcornic/hugo-theme-learn/issues/368

:-)

**Comment by patriotaki** [comment]
> Duplicates: #330
> 
> :-)

thanks! how can i change the colored yellow border to another color?

also it worked for me when i named the file custom-footer.html.

footer.html and custom-header.html did not work for me

why? sorry i dont know much about hugo

thanks

**Comment by patriotaki** [comment]
> Duplicates: #330
> 
> :-)

thank you solved it.

one question tho, it only worked when i named the file custom-footer.html. any other names did not work, why is that?

**Comment by Nightshadelink** [comment]
> one question tho, it only worked when i named the file custom-footer.html. any other names did not work, why is that?

please tell me **which** file you renamed and **how**...

-----

It should not matter if you write your custom stuff in the `footer.html` or the `custom-footer.html`. Technically it should not make any difference. Its just a way of keeping your code clean and easy to maintain. 

Please correct me if i am wrong.

**Comment by Nightshadelink** [comment]
Also: as mentioned in #330 you must add the changes in the footer. This is not a hugo-thing, but more a general JS-related thing. As you can imagine, the Site itself and therefore any content that could be modified via JS must be loaded before it can be modified via JS.
If you write the JS-code in the header for example it would call an element that does not exist yet.

If you want to know anything more about this just google "DOM", "header vs footer" or something like that. W3schools might also be a place to start.


Dont forget to close your issue. ;)

**Comment by patriotaki** [comment]
> > one question tho, it only worked when i named the file custom-footer.html. any other names did not work, why is that?
> 
> please tell me **which** file you renamed and **how**...
> 
> It should not matter if you write your custom stuff in the `footer.html` or the `custom-footer.html`. Technically it should not make any difference. Its just a way of keeping your code clean and easy to maintain.
> 
> Please correct me if i am wrong.

thanks!
