### ISSUE TITLE
Codeblock with horizontal scrollbar

### ISSUE THREAD

**Issue by toplac** [matcornic/hugo-theme-learn#37]
Hi, 

first of all i a really like your theme. 

Is it possible to add a Codeblock with horizontal Scrollbars, e.g. as a shortcode?

**Comment by matcornic** [comment]
Thanks @toplac ,

Did not plan it, but everything is possible !
What is your edge case (to not be satisfied enough with current display for code) ?

I would not mind a PR on this subject if it's blocking for you.
