### ISSUE TITLE
How to increase body font size?

### ISSUE THREAD

**Issue by kpatnayakuni** [matcornic/hugo-theme-learn#391]
Hello,

Greetings!!

I have been trying to increase the body font size, and checking as a trail and error basis by changing where ever I see font-size in theme.css, but I don't see any change in the website. Could you please assist me in increasing the font size of my website a bit.

Thank you.

**Comment by Nightshadelink** [comment]
https://stackoverflow.com/questions/16460990/change-text-font-size-of-whole-page-content

https://css-tricks.com/confused-rem-em/

maybe these two posts will help you. i have not needed that before.

**Comment by kpatnayakuni** [comment]
So, is there no option in the theme itself? I doubt this is a solution.

**Comment by matalo33** [comment]
Nope there's no option built into the theme config. The theme allows you to provide your own css file to override whichever style you like.

Follow the docs at https://learn.netlify.com/en/basics/style-customization/#yours-variant to create a "yours" style.

**Comment by kpatnayakuni** [comment]
Okay, I got it. Thanks for the help! I appreciate it.
