### ISSUE TITLE
Linebreaks in cell does not work

### ISSUE THREAD

**Issue by muffmolch** [matcornic/hugo-theme-learn#412]
Hi
I like to have a line break inside my table cell:

![image](https://user-images.githubusercontent.com/6783248/84865206-1e59ff00-b078-11ea-8521-37d0bf93a0d8.png)

a long time ago this works:

```
| Fruit         | Price                   | Advantages              |
| ------------- | ----------------------- | ----------------------- |
| Bananas       | first line<br>next line | first line<br>next line |
| Bananas       | first line<br>next line | first line<br>next line |
```
But this is the result :-(
![image](https://user-images.githubusercontent.com/6783248/84865340-55301500-b078-11ea-8821-43523372c80c.png)

Do you have any idea how to solve that?

**Comment by ShayNehmad** [comment]
Adding 
```toml
[markup.goldmark.renderer]
unsafe = true
```

should solve it, I think ()

**Comment by muffmolch** [comment]
Thanks! That really fixed my problem

**Comment by ShayNehmad** [comment]
No problem, glad to help 😎
@matcornic perhaps you should add this to the theme's documentation somewhere
