### ISSUE TITLE
Print improvements

### ISSUE THREAD

**Issue by McShelby** [matcornic/hugo-theme-learn#413]
Recently I've spent some time adding CSS improvements for printing. 

Is this something you are interested in? If yes, I'ld set up some PRs for this so you could cherry-pick the things you like.

**Comment by chankeypathak** [comment]
@McShelby Could you share the changes that you made? Possibly with "before|after" screenshots?

**Comment by McShelby** [comment]
Just a short checklist of things that are sub par with current printing. some stuff may be browser related, I am on Windows using FF and Chrome (and sometimes IE11 if I'm in a good mood)

- Text to big, go with DIN saying 11 to 12 pt
- adjust color for notice boxes
- adjust color for codeblocks
- adjust color for table headers
- sidebar removeal (FF)
- next / prev removal
- remove runtime styles to have determinstic print output
- unsticky header

**Comment by chankeypathak** [comment]
Thanks for sharing the details. Can you share the link to the updated repo or your PR?

**Comment by McShelby** [comment]
Fixed in the fork
