### ISSUE TITLE
Error rendering partial in menu.html

### ISSUE THREAD

**Issue by ahrbe1** [matcornic/hugo-theme-learn#42]
I'm getting an error with Hugo v0.20.7 and hugo-theme-learn bc05a6e4035bcc256e0054b1363dc758239635b5.

This was from following the setup instructions here: https://matcornic.github.io/hugo-learn-doc/basics/installation/

--------------------
$ /opt/hugo/hugo serve 

Started building sites ...

ERROR 2017/05/14 19:13:36 Error while rendering "section": template: theme/_default/list.html:2:3: executing "theme/_default/list.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:26:7: executing "theme/partials/header.html" at <partial "menu.html" ...>: error calling partial: template: theme/partials/menu.html:20:28: executing "theme/partials/menu.html" at <$sectionPage.Content>: can't evaluate field Content in type *hugolib.Page

ERROR 2017/05/14 19:13:36 Error while rendering "page": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:26:7: executing "theme/partials/header.html" at <partial "menu.html" ...>: error calling partial: template: theme/partials/menu.html:20:28: executing "theme/partials/menu.html" at <$sectionPage.Content>: can't evaluate field Content in type *hugolib.Page

--------------------

Any ideas? Thanks!

**Comment by matcornic** [comment]
I just tested with latest build version of hugo and latest version of the theme. And I don't get your issue.

Here are the steps I have done:

```bash
# Get the latest build version of hugo (could be unstable)
go get -u github.com/spf13/hugo
# Create hugo site and initialize it with learn theme
hugo new site test-hugo
cd test-hugo/themes
git clone https://github.com/matcornic/hugo-theme-learn.git
cd ..
echo 'theme = "hugo-theme-learn"' >> config.toml
# Create first content
hugo new --kind chapter basics/_index.md
hugo new basics/first-content.md
hugo new basics/second-content/index.md
# Launch website
hugo serve
````

When going to `http://localhost:1313/basics`, I have a working website.

**Comment by matcornic** [comment]
No news since 20 days

**Comment by chrisbenincasa** [comment]
☝️ @matcornic  I followed the steps above and get a `404 page not found` when hitting the `/basics` endpoint when running with `hugo serve`

When running with `hugo server -D` , I get the error from @ahrbe1 

```
) hugo server -D
Started building sites ...
ERROR 2017/07/26 15:58:49 Error while rendering "section": template: theme/_default/list.html:6:16: executing "theme/_default/list.html" at <index .Site.Sections...>: error calling index: cannot index slice/array with type string
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.

ERROR 2017/07/26 15:58:49 Error while rendering "page": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:26:7: executing "theme/partials/header.html" at <partial "menu.html" ...>: error calling partial: template: theme/partials/menu.html:19:54: executing "theme/partials/menu.html" at <$key>: wrong type for value; expected string; got int
Built site for language en:
3 of 3 drafts rendered
0 future content
0 expired content
2 regular pages created
8 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 3 ms
Watching for changes in /Users/christianbenincasa/dev/test-hugo/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop```


NOTE:
```
) hugo version
Hugo Static Site Generator v0.25.1 darwin/amd64 BuildDate: 2017-07-26T15:29:13-04:00
```

The version here is quite different, which could be causing issues.

**Comment by matcornic** [comment]
@chrisbenincasa 

*Extract from README.md*:

Check that your Hugo version is between 0.19 and 0.21 with hugo version.

> From 0.22, Hugo team introduced a long awaited feature: nested sections. As Hugo team deleted some functions on which this theme was based on, this theme fails with current Hugo version. A complete rewrite is needed and is currently under construction. Be aware that this new version will possibly make breaking changes.

> Until the v2 is not out yet, feel free to check Docdock, a great fork of hugo-learn-theme by @vjeantet that works and embraces latest features of Hugo!

**Comment by chrisbenincasa** [comment]
@matcornic whoops thanks for the info and very quick response! I totally missed that section of the docs, sorry!
