### ISSUE TITLE
Tag page is empty

### ISSUE THREAD

**Issue by retorquere** [matcornic/hugo-theme-learn#421]
When I go to `https://<site>/tags/<tagnam>/` I get a blank page. The `https://<site>/tags/` page does list all active tags, but the links all go to empty pages.

**Comment by chankeypathak** [comment]
I'm facing the same issue. I'm using a very old version of this theme though.

- https://tutswiki.com/tags
- https://tutswiki.com/tags/python

The source is available at https://github.com/TutsWiki/source

**Comment by retorquere** [comment]
I'm using the latest "learn" theme.

**Comment by chankeypathak** [comment]
Okay, maybe @matcornic can help debug this.

**Comment by chankeypathak** [comment]
I updated the theme just now and everything seems to work fine. Check out this [python](https://tutswiki.com/tags/python/) tag on the site.

**Comment by retorquere** [comment]
For me the `/tags` page correctly lists all tags, but the `/tags/<tagname>` is empty. What template creates the latter? Maybe I did something in a partial that broke it for me?

**Comment by retorquere** [comment]
I've just checked and I'm on 3efb327

**Comment by muffmolch** [comment]
Do you have already a solution for this?
Tags are not working since hugo v0.72. Als tag-Sites are emtpy :-(

**Comment by muffmolch** [comment]
got it. the tags site got another kind since hugo v0.73.
Just go into 
   `layouts/_default/list.html`

and change 
`{{ if or (eq .Kind "taxonomy") (eq .Kind "taxonomyTerm")}}`
into
`{{ if or (eq .Kind "taxonomy") (eq .Kind "taxonomyTerm") (eq .Kind "term")}}`

**Comment by matalo33** [comment]
Fixed by #444
