### ISSUE TITLE
minify/cleanup source?

### ISSUE THREAD

**Issue by chankeypathak** [matcornic/hugo-theme-learn#432]
Is there a way to minify generated html source e.g. if you open below URL in chrome you'll notice a lot of whitespaces.

[view-source:https://learn.netlify.app/en/](view-source:https://learn.netlify.app/en/)

**Comment by fritzmg** [comment]
https://gohugo.io/hugo-pipes/minification/

**Comment by chankeypathak** [comment]
@fritzmg Thanks! Using `--minify` flag did the trick.
