### ISSUE TITLE
How to disable capitalization of heading?

### ISSUE THREAD

**Issue by chankeypathak** [matcornic/hugo-theme-learn#434]
Where's the option to disable forced uppercase title?

Example: [WRITING AND READING CONFIG FILES IN ANGULAR
](https://tutswiki.com/read-write-config-files-in-angular/)
![image](https://user-images.githubusercontent.com/424822/90046426-145a2280-dcee-11ea-892e-325aa18fa2e2.png)

Note: I only want to disable it on some pages, not all.

**Comment by matalo33** [comment]
This is currently not configurable in the topmatter.

You can disable sitewide by overriding the particular element in your own theme.css (`h1 text-transform`).

As for per-page setting, the only way I can think is to write your own CSS inline in certain pages by adding a custom shortcode like this: https://anaulin.org/blog/hugo-raw-html-shortcode/

Afraid supporting customisation like that is going to be out of scope for this issue tracker.

Good luck
