### ISSUE TITLE
Search error with _index.md pages

### ISSUE THREAD

**Issue by fgiorlando** [matcornic/hugo-theme-learn#44]
when using search, subpages work fine but when the search result points to a chapter index page, the link is incorrect.

For example, 

1. search for `core` in the site http://matcornic.github.io/hugo-learn-doc
2. click on the search result `Basics`

This will result in the wrong URL being served for the search, ie:
https://matcornic.github.io/hugo-learn-doc/basics/_index
NOT
https://matcornic.github.io/hugo-learn-doc/basics

Is there a simple way to fix this behaviour?

**Comment by fgiorlando** [comment]
I did a quick fix for this using an nginx redirect.
It's a kludge but it works:

```nginx
    rewrite ^(.*/)_index$ $1 permanent;
```

**Comment by matcornic** [comment]
Fixed in future v2
