### ISSUE TITLE
difference between fonts and webfonts

### ISSUE THREAD

**Issue by DanielRuf** [matcornic/hugo-theme-learn#486]
What is the difference between these?

https://github.com/matcornic/hugo-theme-learn/tree/master/static/webfonts
https://github.com/matcornic/hugo-theme-learn/tree/master/static/fonts

**Comment by DanielRuf** [comment]
cc @McShelby

**Comment by McShelby** [comment]
The `webfonts` directory is a requirement for the fontawesome fonts (hard coded in the fontawescome.css).

All other theme fonts reside in `fonts` which is okay for me.
