### ISSUE TITLE
Way to prevent listing of sites without title paramter?

### ISSUE THREAD

**Issue by r4dh4l** [matcornic/hugo-theme-learn#488]
Hi,

is it possible to create a sub page but don't list it in the navigation bar? It is somehow possible by not providing the `title:` parameter but then there is a "blank" (and still clickable) point in the navigation bar.

Thanks for this great theme!

**Comment by mirisbowring** [comment]
Did you try the `hidden = true` parameter?
https://learn.netlify.app/en/cont/pages/#front-matter-configuration

This should hide the page from sidebar.

**Comment by r4dh4l** [comment]
> Did you try the hidden = true parameter?

Great, thank you very much! I think this is what I was looking for. I will try this and will report back if it doesn't work as expected.
