### ISSUE TITLE
Strange capitalization issue with search

### ISSUE THREAD

**Issue by zmb3** [matcornic/hugo-theme-learn#50]
While entering a search query, the character immediately following a match is capitalized.

![image](https://user-images.githubusercontent.com/7527103/27052789-7d7f6d78-4f80-11e7-86c4-636480e34f97.png)

In this example, as I type 'introduction' in the search box, the text on the page changes from:
- INtroductIOn
- InTroduction
- IntRoduction
- etc.

**Comment by xxxtonixxx** [comment]
I have the same problem 👍
