### ISSUE TITLE
Update to Hugo version 0.23

### ISSUE THREAD

**Issue by m0d00d** [matcornic/hugo-theme-learn#51]
Starting with Hugo version 0.22 .Site.Sections is not working anymore. Switch to proposal from 

https://github.com/gohugoio/hugo/blob/master/hugolib/site_sections.go#L34

**Comment by zmb3** [comment]
The relevant change: https://github.com/gohugoio/hugo/blob/master/hugolib/site_sections.go#L34

**Comment by victorcoder** [comment]
This renders in this theme only working in the rage of >= 0.19 < 0.22

**Comment by vielmetti** [comment]
I ran into this today.

**Comment by victorcoder** [comment]
All issues seems to be solved in this fork https://github.com/vjeantet/hugo-theme-docdock

**Comment by anthonyfok** [comment]
Hi @matcornic,

Please try to find time to resolve this issue ASAP, as some end user (friend or foe?  :wink:) is already requesting the removal of your theme from themes.gohugo.io, see gohugoio/hugo#3697

As @victorcoder has kindly suggested, the issue has been solved in the fork https://github.com/vjeantet/hugo-theme-docdock

Many thanks!

**Comment by matcornic** [comment]
Hey everyone!

I just mentioned this big issue [in the README](https://github.com/matcornic/hugo-theme-learn/commit/27b99f0f181ea4c7e3a3d01bed4b68c3f5a090ec) of the project to better warn users. This issue will need a lot of work to be done (it's like a complete rewrite). We need to change menu, automatic arrows and breadcrumbs display.

I may rewrite all the theme from code of the great docdock fork.

And thanks for the heads up @anthonyfok, but I don't mind haters ^^ (I only focus on contributors)

**Comment by anthonyfok** [comment]
> And thanks for the heads up @anthonyfok, but I don't mind haters ^^ (I only focus on contributors)

That's awesome!  Thank you @matcornic!

I wrote a comment at gohugoio/hugo#3697 and closed the issue.  :laughing:

**Comment by matcornic** [comment]
Fixed in v2 milestone

**Comment by matcornic** [comment]
@anthonyfok @m0d00d @victorcoder @vielmetti I just released v2, give it a Go https://learn.netlify.com/en/ !
