### ISSUE TITLE
How to configure the menu from config.toml

### ISSUE THREAD

**Issue by kamar535** [matcornic/hugo-theme-learn#52]
Using this theme I can successfully add a weight in the page front-matter.

Usually the menu for a Hugo site can also be configured from the `config.tom` file by adding entries `to [[menu.main]]`, see https://gohugo.io/extras/menus/ 

But, for this theme this does not work, is there another way to configure the menu from `config.toml`?

Hugo version:  0.21

**Comment by matcornic** [comment]
Hello @kamar535 , this theme does not use Hugo menus at all. The menu is automatically generated from sections.

In the FrontMatter of your pages, the `Title` parameter will be used as label of the menu. The weight will be used to order sections in the menu.

https://matcornic.github.io/hugo-learn-doc/cont/pages/#types

**Comment by kamar535** [comment]
Tanks for the answer. 

Maybe the theme documentation could mention https://gohugo.io/content-management/sections/ and that the menu can only be configured from the pages front matter.

**Comment by matcornic** [comment]
Actually, the theme is currently on a rewrite to use latest features of Hugo: nested sections. In the future release, menu will be also generated automatically but infinite level of sections will be possible!

Therefore, the documentation will be updated as well.

Follow #51 for more information.

**Comment by amberalpha** [comment]
This is an old thread but hope it's ok to chip in?  I like Learn a lot and just want to simplify the (side) menu, eliminating the parts *not* generated from my content i.e. everything under 'More' and the search box.  Must be an easy way... I get a bit lost in the docs.

**Comment by acuvic** [comment]
> This is an old thread but hope it's ok to chip in? I like Learn a lot and just want to simplify the (side) menu, eliminating the parts _not_ generated from my content i.e. everything under 'More' and the search box. Must be an easy way... I get a bit lost in the docs.

Hi Amberalpha, you've probably found the solution. Just delete any [[menu.shortcuts]] in config.toml
My own question to @matcornic : firstly a great theme, and I've used 4 different ones on live sites, I'll contribute. Question is can I change the "MORE" wording in menu to "Latest Addition" ? Been searching for ages but cannot find. Thanks

**Comment by acuvic** [comment]
Ignore last question - found "More" is set in the i18n folder under en.toml
