### ISSUE TITLE
Google Analytics in the exampleSite

### ISSUE THREAD

**Issue by lil5** [matcornic/hugo-theme-learn#528]
Please at least state that Google Analytics are added to `/exampleSite/partials/custom-footer`, not doing so makes it very difficult know if someone knowingly added analytics to their site.

Preferably I would ask for that to be removed entirely, especially if you are not looking at those analytics!

**Comment by McShelby** [comment]
Feel free to check out [the fork](https://github.com/McShelby/hugo-theme-relearn) with a lot of bug fixes aaand: GA free ;-)
