### ISSUE TITLE
Configuration of the appearance of the copy-to-clipboard icons 

### ISSUE THREAD

**Issue by kamar535** [matcornic/hugo-theme-learn#54]
Thanks for a great Hugo theme! 

For my site I don't want the copy-to-clip-board icon for inline `code` tags but keep it for `code` tags within `pre` tags. I was able to achieve this by adding this css: 

```
:not(pre) > code + span.copy-to-clipboard {
    display: none;
}
```

It would be really handy if it would be possible to configure the appearance of the copy-to-clipboard icons from the `config.toml` file.  Maybe this could be considered for future versions of the theme.

**Comment by matcornic** [comment]
Fixed in v2 8dccd68886ab09ea4b9bb755c5b0bca3758b269c
