### ISSUE TITLE
Is it possible to create globally available variables?

### ISSUE THREAD

**Issue by hellt** [matcornic/hugo-theme-learn#58]
Is it possible to create a global variables (useful for global links)?
For instance throughout my documentation articles I refer to my master branch, and I want to have it as a variable, rather than pasting an absolute link.

refer to this example

```
[my repo][my_repo_link]

[my_repo_link]: {{params.my_global_repo_link}}
``` 

This is possible in gitbook for instance and has a huge importance as to my opinion. Could it be that I can put something in `[params]` and use it like that?

**Comment by matcornic** [comment]
This theme does not provide any shortcode to do that. Maybe, it's possible with just plain Hugo. Go ask in the [forum](https://discourse.gohugo.io/)

One way (maybe not the best) :

1. Create a shortcode that will get a key as a parameter. This shortcode will search in `.Site.Params` for the given key
2. Use that shortcode in your Markdown content.

I'm interested in the solution. If it's not possible with pure Hugo, I (or you with a PR) could create the given shortcode in this theme.

**Comment by hellt** [comment]
Seems like a custom shortcode would be needed to use `.Site.params` site variable.
I am new to Hugo/Go, so I'll try to play with custom shortcodes, but no PR guaranteed =)

**Comment by matcornic** [comment]
@hellt Shortcode `siteparam` is available: https://learn.netlify.com/en/shortcodes/siteparam/
