### ISSUE TITLE
Search enhancements

### ISSUE THREAD

**Issue by hellt** [matcornic/hugo-theme-learn#59]
Hi!

1. Is Search not working on mobile? Tested with Android/Chrome and nothing pops up during the characters typing in the search field

2. Search on a desktop appears only as a drop down with top-10 results. Is it possible to rather display a page with search results where >10 items could be displayed?

**Comment by matcornic** [comment]
Hello !

1. :thinking: I tested with Safari/Chrome on iPhone and its works. But I just asked a friend with an Android and he get this behavior too. I created a separate issue #60 (but I don't have an Android phone at home ^^)
2. It's not planned yet, but i could be a great asset. Although, I think two modes should be available as it's faster to go to a page with current search mode.

**Comment by matalo33** [comment]
Fixed in #75
