### ISSUE TITLE
Search pop-up does not show on Android+Chrome

### ISSUE THREAD

**Issue by matcornic** [matcornic/hugo-theme-learn#60]
Help Wanted, I don't have an Android phone 😄

**Comment by EnigmaCurry** [comment]
It's odd, the search does not appear at all in chrome or firefox with the Google keyboard, but if I switch to any other keyboard (hacker keyboard) it still does not work well, but it works as soon as you press a single backspace key. Search for 'image' and nothing shows up. Backspace once, so the search is 'imag' and the results show. But only with a non-Google keyboard.

**Comment by EnigmaCurry** [comment]
So it appears an issue entirely in the upstream horsey library. I get the same behaviour as I described above on their example page: https://bevacqua.github.io/horsey/

**Comment by EnigmaCurry** [comment]
In #75 I've replaced horsey with pixabay autocomplete, and it works!
