### ISSUE TITLE
Support same page anchor like ReadTheDocs

### ISSUE THREAD

**Issue by klausenbusk** [matcornic/hugo-theme-learn#68]
Hello

I'm wondering if this theme support same page anchor link.
Something like: https://borgbackup.readthedocs.io/en/stable/installation.html
Where the menu point to the title on the same page, if that make any sense...

Kristian

**Comment by matcornic** [comment]
I don't really understand your question, but I will try to give an answer anyway.

A **table of content** is available in the fixed navbar, at the left of the current page title.

In 2.0.0, it's automatically avalaible on default pages but can be disabled by setting `toc = false` in the Front Matter of the page. Prior to 2.0.0, you have to set the parameter to true.

See page [Markdown](http://learn.netlify.com/en/cont/markdown/) for example

**Comment by klausenbusk** [comment]
> I don't really understand your question, but I will try to give an answer anyway.

I want something similar to: https://borgbackup.readthedocs.io/en/stable/installation.html , you can see the "headline" in the menu. Ex clicking `Pre-Installation Considerations` goes to the `Pre-Installation Considerations` headline on the same page.
I'm wondering if this theme can do the same?



> In 2.0.0, it's automatically avalaible on default pages but can be disabled by setting toc = false in the Front Matter of the page. Prior to 2.0.0, you have to set the parameter to true.

That seems to be something else. `toc = false` remove the page from the menu as I understand from the example site.


Sorry if I'm confusing, I'm pretty new to this and all the terms.

**Comment by matcornic** [comment]
The left menu contains only pages. For anchors of the current page, it's automatically generated like this: http://recordit.co/KTJPaCAF92
