### ISSUE TITLE
Logo question

### ISSUE THREAD

**Issue by gristel** [matcornic/hugo-theme-learn#7]
Hi,
sorry if this is a dumb question, but how can I change the logo and still make it fit?
Thanks!

**Comment by gristel** [comment]
Sorry I overlooked something

**Comment by epogrebnyak** [comment]
I have the same question as a theme beginner user. I experimented with favicon.png, but so far got a result that the logo changed from Learn to some hidden default 'Grab' and that is not an intended result. 

I think documentation begs for "How to change landing page logo" section.
