### ISSUE TITLE
[Shortcode] Tabs

### ISSUE THREAD

**Issue by thibaultmeyer** [matcornic/hugo-theme-learn#70]
Hello,

Please add horizontal tabs. This feature is useful for an API documentation to give code sample for multiple languages (ex: Shell, Python, Java, ...)

![image](https://user-images.githubusercontent.com/1005086/30468545-40d65dbc-99ec-11e7-847b-df6791532da5.png)

**Comment by matcornic** [comment]
Nice idea, I agree that it would a great improvement

**Comment by fritzmg** [comment]
👍 for this. Kubernetes also implemented this for their Hugo docs: https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#tabs :)

**Comment by MichaelStott** [comment]
Anything we can do to help get #386 merged @matcornic?
