### ISSUE TITLE
Search is not working on live

### ISSUE THREAD

**Issue by webuimaker** [matcornic/hugo-theme-learn#78]
Hi team,

Automatic search popup is not working on live but its working on local. 
![image](https://user-images.githubusercontent.com/14191763/31253792-c90aee66-aa43-11e7-91b8-10cf84aa2b2d.png)

live 👍 
![image](https://user-images.githubusercontent.com/14191763/31253836-e7dd93d4-aa43-11e7-9087-fcc31e5f213f.png)

please let me know where i mistake.

**Comment by 0xbaadf00d** [comment]
It seems search only work for the primary language too.

**Comment by jcw** [comment]
Are you running in HTTPS mode, by any chance?

I ran into the same problem (#76) until I noticed that I had set `baseurl` to "http:..." instead of "https:...". Once fixed in `config.toml`, it all started to work brilliantly.

**Comment by webuimaker** [comment]
Thanks Both of you for help. Now search is working on live too.
