### ISSUE TITLE
Cannot override template breadcrumb 

### ISSUE THREAD

**Issue by kamar535** [matcornic/hugo-theme-learn#82]
I try to override `themes/hugo-theme-learn/layouts/partials/header.html` with `layouts/partials/header.html`. 

Modifying the `breadcrumb` template in the `{{define "breadcrumb"}} ...  {{ end }}` has no effect.  Somehow the `breadcrumb` template defined in `themes/hugo-theme-learn/layouts/partials/header.html` is still in use. 

If I rename the template to `breadcrumb2` in `layouts/partials/header.html` it works. Is this expected behaviour of the Hugo templating system and if so, where can I learn more?

**Comment by kamar535** [comment]
I think this is probably not specific to the Hugo Learn Theme and therefore also posted here: https://discourse.gohugo.io/t/cannot-override-define-breadcrumbs-in-hugo-learn-theme/8889

**Comment by matcornic** [comment]
@kamar535 Seems to be from Hugo: https://github.com/gohugoio/hugo/issues/3996 
I let you close the issue when you want (now or when the bug is fixed in Hugo ^^)
