### ISSUE TITLE
Issue with unresponsive breadcrumb

### ISSUE THREAD

**Issue by siddhantrimal** [matcornic/hugo-theme-learn#83]
I thought the issue was limited to my own blog that I made with hugo-learn, so I kept quiet about it for months. Now on close inspection, it is apparent that the problem is in the theme itself.

Renders breadcrumb and 'Edit this page' in different lines (or out of layout bounds) in my Samsung Galaxy S7's pretty huge screen. looks ugly. Sometimes messes with the toggle  navigation button functionality.

Similar result when rendering in Mobile View with Chrome.

![Official Learn Theme Demo Page Rendering Poorly on S7](https://i.imgur.com/iOk0Vi0.jpg)

**Comment by siddhantrimal** [comment]
> This issue has been here for long. ___Updating___ the issue with a `gif` so that you get a clearer idea, if it wasn't apparent before.

## This is what I'm taking about. Breaks the same way on my S7 Edge. It's heart-breaking 😞 

![breaksadsmall](https://user-images.githubusercontent.com/18209220/32885997-65081bae-cae7-11e7-9638-e4df153da722.gif)

### Ps. I don't know what's wrong with it. This is the only reason why I haven't switched from DocDock.

**Comment by matcornic** [comment]
Thanks @siddhantrimal for reporting this. I think we should hide the breadcrumb on mobile, what do you think about it ?

**Comment by siddhantrimal** [comment]
@matcornic Please include a `hideMobileBreadcrumb:true` toggle instead, if possible. I have recently started using the DocDock theme on some other project, and it does not have this bug; I just might find out what's wrong with it. I'll try to look for a solution on my end.

![capture](https://user-images.githubusercontent.com/18209220/32929507-900b4030-cb80-11e7-9b8a-72160b72380a.PNG)

**Comment by matcornic** [comment]
I choose to remove text on Mobile : it's much clearer. I fixed as well the problem of the width of top-bar that did not resize on window change.

<img width="397" alt="capture d ecran 2017-11-23 a 19 52 41" src="https://user-images.githubusercontent.com/3520706/33186187-f0e12b66-d087-11e7-85be-f16de0a80225.png">
