### ISSUE TITLE
Search does not work when pasting in text

### ISSUE THREAD

**Issue by JasonTheAdams** [matcornic/hugo-theme-learn#92]
If the user copy and pastes text into the search field, it doesn't trigger the live-search options to display. If any keys are pressed afterwards it starts working, but there's no immediate result.

It would be great to have pasting text into the search field act the same as typing into it.

**Comment by pgorod** [comment]
Just tried this, and it worked well for me... as soon as I hit Ctrl-v to paste, the find-as-you-type results appeared, and correctly.

**Comment by matcornic** [comment]
I don't reproduce either. Could you tell us your environment ?

**Comment by JasonTheAdams** [comment]
Using Chrome 63 on MacOS High Sierra. Here's the site: https://piklist.github.io/Piklist-Documentation/

Curious what the issue is since it works for you. Does our site work?

Thanks!

**Comment by pgorod** [comment]
Pasting on your site works for me on Firefox 56 on Windows.

Maybe try using Chrome in incognito mode, which disables extensions, to see if it solves it for you.

**Comment by matcornic** [comment]
Weird, this is working with https://learn.netlify.com/en/ (in Chrome and Firefox), but your site does not work either on my Chrome.

- What version of the theme do you use ?
- Did you override some assets ?

**Comment by JasonTheAdams** [comment]
Updating the theme fixed the issue. Looks like the autocomplete lib was changed since we cloned in late summer. Thanks!
