### ISSUE TITLE
Remove github related icons from menu

### ISSUE THREAD

**Issue by JeanBilheux** [matcornic/hugo-theme-learn#95]
Is it possible to remove the github related icons (download, fork, stars...) icon from left menu (see green box in screenshot)
![screen_shot_2017-12-22_at_7_49_10_pm](https://user-images.githubusercontent.com/1138324/34315699-b123cc50-e751-11e7-8897-d04111a42d84.png)

**Comment by matcornic** [comment]
These buttons come from https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/partials/menu-footer.html

Just override the `menu-footer.html` partial by adding a new `menu-footer.html` in your site `partial` folder. You can let it empty or add content as you want.

**Comment by JeanBilheux** [comment]
Thanks a lot. 

I have been looking for this kind of tool for a while and your library is really amazing. The video tutorials are also awesome. Great job.
